
# Projeto Engenharia de Analytics da empresa Adventure Works por Felipe Almeida.
# Documentação completa da IDE DBT: https://docs.getdbt.com/docs/configuring-models
name: 'dbt_adventure_works'
version: '1.0.0'
config-version: 2
profile: 'default'

# As configurações abaixo especificam onde o DBT deve procurar por diferentes tipos de arquivos
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# As configurações abaixo especificam onde serão inseridos os arquivos SQL compilados
# e quais pastas devem ser limpadas pelo comando "dbt clean".
target-path: "target"  # diretório dos arquivos compilados
clean-targets:         # diretórios a serem removidos pelo "dbt clean"
  - "target"
  - "dbt_packages"

# Nas configurações abaixo especifica-se em quais pastas e quais modelos serão criados pelo "dbt build"
# Essas configurações podem ser sobrescritas nos modelos individiduais pela macro `{{ config(...) }}`
models:
  dbt_adventure_works:
    sources:
      +materialized: view

    stagings:
      +schema: aw_stg
      +materialized: table

    marts:
      +materialized: table

seeds:
  dbt_adventure_works:
    sap_adventure_works:
      +schema: aw_seeds_sap